### ISSUE TITLE
Add the number of entries on the people page

### ISSUE THREAD

**Issue by Thrainsa** [alakajam-team/alakajam#119]
We could add the number of entries next to the user name on the people page to see if someone has entries. Separatings Alakajam entries and external entries could be a good idea

![alakajam1](https://user-images.githubusercontent.com/7467127/30335388-852e3306-97e2-11e7-95d5-4aef79648de4.png)

**Comment by mkalam-alami** [comment]
Tip: joining on `user_role` might suffice
