### ISSUE TITLE
Allow to disable theme voting before displaying results

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#141]

**Comment by Aurel300** [comment]
I wonder why we need this x)

**Comment by Aurel300** [comment]
So, implementation-wise:

- [x] another possible value for `status_theme`: `closed`
- [ ] admin interface allows choosing `closed`
- [ ] the `/themes` page displays themes in the chosen order (or random if none?), but doesn't allow users to arrange them anymore
- [ ] have a notice on `/themes`, something like "The votes are being counted" ? "The voting is now closed" ?
- [ ] front page: "Theme will be announced soon" ?
- [ ] check other templates and code that depends on `status_theme` values

Have I missed something?

**Comment by mkalam-alami** [comment]
Looks good. Some precisions:

> front page: "Theme will be announced soon" ?

Not needed, the big text/link you're probably thinking is the "Call to action" field that is written manually.

> check other templates and code that depends on `status_theme` values

Apart from maing sure server-side that people can't vote (e.g. by forging requests), I don't think there's anything particular to do.
