### ISSUE TITLE
Editing my entry made its links disappear

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#143]
I'm not going to try reproduce this because I'm in a hurry, but I _think_ I did the following:

- create an entry with two links
- save it
- edit it
- change the screenshot
- save it again

After this, both links were gone.

Sorry these are not 100% waterproof repro steps, but I'm in a hurry, there's a game jam on!

**Comment by ttencate** [comment]
Also the platforms were gone at some point.

**Comment by mkalam-alami** [comment]
I can reproduce by disabling JavaScript (equivalent to saving while the page is still loading)
