### ISSUE TITLE
Very easy to forget to save ratings

### ISSUE THREAD

**Issue by yumaikas** [alakajam-team/alakajam#151]
It is very easy to forget to save your ratings for an entry, as changes in them aren't required to be saved before navigating away from the ratings page, or before submitting a comment. 

I can think of few different ways to try to resolve this:

1. Alert before navigating away from the page.
2. Saving the rating in a cookie or in browser local storage, and putting some text up to indicate that the rating has *not* been saved.
3. Automatically saving the ratings to the database using AJAX

**Comment by Eremiell** [comment]
I'd add that as discussed before on IRC, the same is an issue for final theme voting phase.

**Comment by mkalam-alami** [comment]
Thanks, at least for now we'll go with with the easy alert popup solution.

**Comment by ttencate** [comment]
Reopening this because it even confused me, and I wrote it: I forgot to save the ratings, went on to type a comment, tried to save the comment and got the popup.

Perhaps comments and ratings should be in the same form, so that either save button can be used to save both.

**Comment by ttencate** [comment]
Closing in favour of the more specific #181.
