### ISSUE TITLE
Performance: static CSS and JS have max-age=0

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#152]
E.g.

```
$ curl -I https://alakajam.com/static/css/bootstrap.min.css
HTTP/1.1 200 OK
...
Cache-Control: public, max-age=0
Last-Modified: Tue, 20 Jun 2017 21:08:49 GMT
ETag: W/"1d970-15cc7561f1c"
...
```

This means they'll be re-requested on every page view. A simple improvement would be to set some not so high value, like 1 hour (`max-age=3600`).

Much better would be to add file hashes to the URL, so we can set a near-infinite expiry.

[A good guide on cache control headers.](https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers)

**Comment by ttencate** [comment]
Related: the server sends the full response body anyway (rather than a "304 Not Modified") even if the client sends appropriate `If-Modified-Since` and `If-None-Match` headers. It seems that the `If-None-Match` header is triggering this:

```
$ curl -H 'If-Modified-Since:Wed, 30 Aug 2017 20:29:06 GMT' -I https://alakajam.com/static/css/bootstrap.min.css
HTTP/1.1 304 Not Modified
...
$ curl -H 'If-None-Match:W/"262cf-15e34d54876-gzip"' -H 'If-Modified-Since:Wed, 30 Aug 2017 20:29:06 GMT' -I https://alakajam.com/static/css/bootstrap.min.css
HTTP/1.1 200 OK
...
$ curl -H 'If-None-Match:W/"262cf-15e34d54876-gzip"' -I https://alakajam.com/static/css/bootstrap.min.cssHTTP/1.1 200 OK
...
```

**Comment by mkalam-alami** [comment]
Node itself seems to send 304s correctly, so the issue probably lies in the Apache config:

### Local server

![local](https://user-images.githubusercontent.com/694508/30798090-8aabe512-a1d8-11e7-99eb-74a5125e699c.PNG)

### Live site

![remote](https://user-images.githubusercontent.com/694508/30798092-8d0cf148-a1d8-11e7-8f9b-dfab9291ed43.PNG)

**Comment by ttencate** [comment]
Everything is coming from cache now. JS and CSS have a TTL of 14400 seconds (4 hours). Probably this is @mkalam-alami's doing with the CloudFlare setup :+1:
