### ISSUE TITLE
dashboard shows comments multiple times

### ISSUE THREAD

**Issue by Laguna1989** [alakajam-team/alakajam#164]
Hi,

the dashboard shows comments on my game multiple times as you can see in the attached screenshot. I don't know if this is due to the other user editing the comment or if it should be that way?
![error_alaka](https://user-images.githubusercontent.com/2394228/30822247-6638a3aa-a228-11e7-9cb4-cc4ce89d6514.png)

So Far...
Laguna

**Comment by mkalam-alami** [comment]
It was a little issue with the SQL query, can you confirm it is now fixed?

**Comment by Laguna1989** [comment]
Worked like a charm! Thank you alot!


Am 25.09.2017 um 21:17 schrieb Marwane Kalam-Alami:
