### ISSUE TITLE
Confirmation dialog when navigating away from unsubmitted forms shouldn't pop when the textarea is empty

### ISSUE THREAD

**Issue by NiciusB** [alakajam-team/alakajam#176]
Example: If you go to a post, and start writing a comment, the beforeunloadHandler is set. But if you later decide not to comment the post, and leave the textarea blank, the confirmation dialog shouldn't pop.

However, you will lose the option to Ctrl+z to recover the  text you wrote, so maybe the confirmation is intended?

I took a look at the client/common/warn-on-unsaved-changes.js file, and it's simple to fix it for single-input forms, but not for forms with many inputs

**Comment by ttencate** [comment]
Ack, I was hoping this wouldn't bother people. To fix this, I'll just grab the value from all the inputs when the form is loaded, and only throw up the dialog if any input's value changed (or inputs were added/removed). That would not only cover this case, but cases of aborted/undone edits as well.
