### ISSUE TITLE
Allow submitting ratings and comments at the same time (or submit ratings async)

### ISSUE THREAD

**Issue by SmBe19** [alakajam-team/alakajam#181]
I usually rate a game and comment at the same time and don't save in between. When I then try to submit my comment it tells me the comment will be lost (as also is the case). It would be nice to be able to submit both at once (like the old LD site) or submit the ratings async (like the new LD site).

Btw. I really like the website and it does many things way better than the new LD site. Thank you!

**Comment by mkalam-alami** [comment]
Related to #151, indeed letting people submit both at the same time would be best.

Glad you like the site!

**Comment by mkalam-alami** [comment]
- [ ] Reorganize form tags client-side
- [ ] Support commenting & rating simultaneously server-side
- [ ] Add target anchor dynamically in JS before submitting?

**Comment by mkalam-alami** [comment]
Submitting comments after rating an entry now works.
