### ISSUE TITLE
Post character limit is too short

### ISSUE THREAD

**Issue by Aurel300** [alakajam-team/alakajam#187]
I was just mirroring a post-mortem blog entry from my blog, and after submitting the post (as a draft), it barely fit half of it. Why is the limit 10000 characters? It seems extremely limiting to me. We can easily make it 100000 and even if people generally posted posts of such length, the data this would consume would be nowhere near the data taken by avatars, hotlinked images, external media, etc.

**Comment by mkalam-alami** [comment]
To be honest it was arbritrarily set. Why not expand the size to 100.000, espcially now that we have the JS bit that adds an "expand" button to long posts.

> Technical note: this will require a migration that runs a raw SQL query, due to knex unsupporting modifying columns.

**Comment by Aurel300** [comment]
Hmm, why are the alter migrations

    if (config.DB_TYPE === 'postgresql') {
      await knex.raw('ALTER TABLE setting ALTER COLUMN value TYPE varchar(10000)')
    }

PostgreSQL only?
