### ISSUE TITLE
JSON API: Search users by title

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#188]
Requested for AlaskaJam/DaFluffyPotato's IRC client

**Comment by Aurel300** [comment]
What should the endpoint URL be? `/api/findUserByDisplay/:name` ?

**Comment by mkalam-alami** [comment]
What about `/api/user/?title=xxx`?

That way we can `/api/user/` into a general endpoint for searching users (why not supporting later stuff like `eventId` for searching all people who entered the event, etc.).
