### ISSUE TITLE
Thumbnail system

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#189]
> Requires #162 

- [ ] When setting the picture of an entry, generate a thumbnail next to it with a specific suffix
- [ ] Use the thumbnail for entry thumbnails & post headers
- [ ] Add a route to make lazy loading picture thumbnails work, or generate all thumbs retroactively

**Comment by Thrainsa** [comment]
I think it could be also a good idea to make it possible to deactivate the gif in preview for bad internet connexion.
To view the game page for event 1st alakajam, you need to download 16.9MB.
I think it could be possible to get the first frame of the gif and use it as thumbnail. (same as simplified html in gmail for slow connexions)

**Comment by mkalam-alami** [comment]
Fixed by  #385
