### ISSUE TITLE
"EventEmitter memory leak" messages / Replace node-formidable library

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#19]
Node sometimes logs warnings like:

```
(node:8088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 field listeners added. Use emitter.setMaxListeners() to increase limit
(node:8088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 file listeners added. Use emitter.setMaxListeners() to increase limit
(node:8088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
```

It must be worth investigating.

**Comment by mkalam-alami** [comment]
Not that I know of... I'll let you know if I reproduce this again.

**Comment by mkalam-alami** [comment]
Still there on Windows 7 / Node 7.10.0

**Comment by mkalam-alami** [comment]
These errors seem to be related to https://github.com/felixge/node-formidable/issues/422. I think they only happen (albeit randomly) when uploading files.

The lib is not really maintained anymore, so between that and a couple issues I had maybe it's best to switch to https://github.com/expressjs/body-parser + https://github.com/expressjs/multer

**Comment by fabiobusnello** [comment]
What is linked to the formidable is not a bug but rather a warning, when you send form, regardless of file or inputs 11 times it returns this memory reminder, it is likely to be a warning of attack ddos

**Comment by mkalam-alami** [comment]
@fabiobusnello Thanks for the clarification!
