### ISSUE TITLE
Store entry counters on events

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#194]
Make it possible to show without recomputing it every time:

* Entry count in the event
* Entry count per division in the event

**Comment by Aurel300** [comment]
- [ ] add `count_total`, `count_solo`, `count_team`, `count_unranked` to `event` table (migration)
- [ ] ensure any entry modification updates the counts:
  - division change
  - draft -> public (we shouldn't count draft entries)

**Comment by Aurel300** [comment]
if (config.DB_TYPE !== 'postgresql') {
      return
    }
    for (let type of [
      'total',
      'solo',
      'team',
      'unranked'
    ]) {
      await knex.raw(`
        WITH result AS (
          SELECT event.id, entries.count
          FROM event
          INNER JOIN (
            SELECT COUNT(*) AS count, event_id
            FROM entry
            ${type === 'total' ? '' : 'WHERE division = "' + type + '"'}
            GROUP BY event_id
          ) AS entries
          ON entries.event_id = event.id
        )
        UPDATE event
        SET count_${type} = result.count
        FROM result
        WHERE result.id = event.id;`)
    }

Does this look alright? I can't test it with SQLite cause it doesn't like the subquery I think …

**Comment by ttencate** [comment]
Do we know that this is actually a cause for concern and warrants the additional headache of keeping everything in sync? If the database has an index on `entry.event_id`, I would think it can count those very very quickly, especially because no actual data from the entry needs to be fetched.

I'd recommend to look at query plans and execution times first. Premature optimization and all that :)

**Comment by Aurel300** [comment]
I was wondering about that myself. It certainly shouldn't make a difference until there are loads of events … Even so, it might be nice to be able to query a single table as opposed to:

- getting all the events via SQL
- javascript to loop through them
- for each event do a count via a separate SQL query

**Comment by Aurel300** [comment]
Alternatively, we could set the count only when an event's `status_entry` is set to `closed`, and keep doing what we're doing with the live events.

**Comment by mkalam-alami** [comment]
@ttencate Requesting it every time is probably quite fast yes, but since it's important info I'd say having it done gives us more freedom to display it wherever we want - a bit like comment counters. The latter have been reasonably easy to set up, so I wouldn't be concerned with entry counts.

@Aurel300 The migration looks ok! Since it's a one shot thing, I wouldn't have minded making 4 requests per event either. For updating counters throughout the event I assume the query is more simple? Like a knex version of:

```
update event set count_xxx = (select count(*) from entry where event_id = ${event_id} and division = 'xxx')
```

(or even using the Bookshelf API to do 4 counts then 1 update, which is slightly slower but who cares)

**Comment by ttencate** [comment]
> Even so, it might be nice to be able to query a single table as opposed to:
>
> * getting all the events via SQL
> * javascript to loop through them
> * for each event do a count via a separate SQL query

Yeah, that O(n) stuff is not nice for sure. Can't Bookshelf do a join where it just counts entries without fetching them? Otherwise can we pass a handwritten query to Knex?

In my experience, keeping denormalized stuff in sync is always a pain. It's too easy to forget some edge case here or there. Or to add edge cases later without even realizing that the denormalized data is impacted. But I'm not coding this so I'm happy to be proven wrong ;)

**Comment by mkalam-alami** [comment]
> Can't Bookshelf do a join where it just counts entries without fetching them? Otherwise can we pass a handwritten query to Knex?

Yep we could either count them with Bookshelf (though 1 query per division) or knex (with I assume a single clever query). If we go down this route we could also solve possible future perf issues by caching the service call, so honestly I don't have strong feelings for either solution.

**Comment by mkalam-alami** [comment]
I ended up finishing this one, mostly because I'm reworking at the same time how divisions work (#206).
