### ISSUE TITLE
Display prettier trophy icons for voting results

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#195]
See pictures `trophy_1, 2 & 3.png` in the `static/images` folder.

**Comment by Aurel300** [comment]
How's that?

![](https://i.imgur.com/ezcqUum.png)

**Comment by mkalam-alami** [comment]
Wow great work!

* **Jamician:** I'll start with the one I have more mixed feelings with - I personally find the original has more character, though we can gather more opinions from the community. Still, your staff looks great and could probably be integrated in the current logo.

![jamician-v2](https://user-images.githubusercontent.com/694508/31165979-530f31f6-a8ed-11e7-88f7-ab13ff3b9a73.png)

* **Medals:** Excellent. For the entry page, my favorite would be the 3rd column. The simpler 2nd column could maybe be used in entry thumbs [a bit like LDJam does](http://ldjam.com/events/ludum-dare/39/results)?
* **Trophies:** Great art as well, they should fit the results page well. With the current layout we might need to add a drop shadow to prevent possible contrast issue with the background picture. Though I think you had something specific in mind regarding how to arrange them in that page?

**Comment by Aurel300** [comment]
![](https://i.imgur.com/QXbu4VE.png)

(ignore the `i` icon, it's not finished / pretty)

- I tried using prettier colours but still keeping the Jamician shape with the third variation
- Smaller medals for smaller thumbs? I guess the 2nd column of big ones can also be used – they can overlap each other if there are multiple
- Heart on / off for post liking, if we add it :)
- Yes, I had something in mind with the trophies, I will make a concept / CSS when I get to it

**Comment by mkalam-alami** [comment]
I like the new Jamician variation!

Also, maybe that was your intent from the start, but instead of cutting these into sprites we can probably set up a CSS spritesheet.

**Comment by Aurel300** [comment]
I was thinking something like:

![](https://i.imgur.com/9pSUv5R.png)

**Comment by ttencate** [comment]
Just want to say that these graphics are absolutely beautiful. Nitpick: the misalignment is not strong enough to look intentional. I would either exaggerate the vertical offset more (maybe draw a podium beneath?), or go for another layout altogether (e.g. 1 above 2 above 3, with the trophies to the side).

**Comment by Aurel300** [comment]
With more vertical offset:

![](https://i.imgur.com/gj9FvLC.png)

And medals in the rankings:

![](https://i.imgur.com/0ZKOnC3.png)

**Comment by Aurel300** [comment]
For now I think this is closed.
