### ISSUE TITLE
Discussion: should Markdown treat a single line break as a line break?

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#202]
In Markdown, like in HTML, a single line break counts as a space in the output. But when writing a post (and presumably in other contexts where Markdown is used), a single line break in the input produces a line break in the output as well.

This is mostly an issue when copy/pasting content from elsewhere, e.g. my own blog, where these line breaks are ignored as they should be.

I'm not sure if this is an issue with SimpleMD, the server-side Markdown converter, or both.

I noticed that GitHub has the same behaviour, while StackOverflow does not; these are on distinct lines in my input:

test
test
test

**Comment by mkalam-alami** [comment]
On the server side, Showdown [has been configured](https://github.com/alakajam-team/alakajam/blob/master/core/forms.js#L55) to use these Github-like new lines, so it can be changed. However I have set that on purpose to go with what is I think the most intuitive - the double-space trick to force new lines is quite obscure to non-coders. I think accessibility is what pushed Github to do that as well.

Client-side, the SimpleMDE preview is not customized - while it has some inconsistencies with the Showdown config, it indeed seems to do like Github by default.

Regarding copy/pasting, if we fix it for pure Markdown sources, we'll break other sources like Github anyway, so nothing would be perfect... My personal preference would be to leave it as is!

**Comment by ttencate** [comment]
Fair enough! I started out with "hey, this is a bug", then noticed that GitHub does the same thing, which got me thinking... now I'm convinced it's better this way.
