### ISSUE TITLE
Announcement: display publish date instead of creation date

### ISSUE THREAD

**Issue by Laguna1989** [alakajam-team/alakajam#230]
Hi there,
the announcement thumbnail in the top left corner of the header displays the creation date of an announcement post instead of the publish date of the announcement.  This could be misleading if there is a reference to the  date ("starting now", ...) is made in the post.

**Comment by mkalam-alami** [comment]
Nice find!

![2018-02-17_16h24_35](https://user-images.githubusercontent.com/694508/36342452-1c548558-13ff-11e8-8d1a-ab5e82481777.png)
