### ISSUE TITLE
Alakajam schedule infographic

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#237]
Have a pretty presentation of schedule, to be used in the [rules page](https://alakajam.com/article/alakajam-competition-rules) + the [schedule posts](https://alakajam.com/post/264).

Maybe something like that but prettier & more informative:

![clipboard02](https://user-images.githubusercontent.com/694508/36534268-5a1234ec-17c6-11e8-88dd-458937ff01f8.jpg)

A generic version would just mention timing with "D-14", "D+2" etc. While we would instanciate the graphic with actual dates for each event.

**Comment by ttencate** [comment]
Would be cool with some small illustrations:

* Theme submissions and voting: the three idea boxes, and some red/green buttons next to some themes (represented as rectangles, not actual words)
* Theme shortlist ranking: a list with the draggable "=" handles on the left
* Jam: last panel of [this comic](http://weknowmemes.com/wp-content/uploads/2012/04/come-outside-chris.gif) ;)
* Submission hour: an upload icon
* Review and ratings: a list of star ratings
* Results: Aurel's awesome trophy graphics

**Comment by mkalam-alami** [comment]
Pretty little illustrations would be great indeed! Here are possibly reusable assets (or at least for inspiration) https://alakajam.com/post/269/2nd-alakajam-wallpapers?editComment=1368#c1344

**Comment by mkalam-alami** [comment]
Done, here's what it looks like. I went for the easy route with the icons:

![](https://camo.githubusercontent.com/6487704891e2348705d7cbbc937d3cf93717fb2f/68747470733a2f2f7374617469632e616c616b616a616d2e636f6d2f7374617469632f70726573736b69742f696d616765732f7363686564756c652d696e666f677261706869632e706e67)

The source document is a presentation in Google Drive
