### ISSUE TITLE
Fix overflows in event headers

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#246]
- [ ]  If the announcement title is longer than a certain size, just replace the end with three dots (I think CSS can do that?)
- [x] Tablet-width header breaks:

![clipboard02](https://user-images.githubusercontent.com/694508/36777522-1351d9d8-1c6a-11e8-90db-ce928676cf59.jpg)

**Comment by olivier-grech** [comment]
Yes, CSS can do that: https://www.w3schools.com/cssref/playit.asp?filename=playcss_text-overflow&preval=ellipsis

**Comment by mkalam-alami** [comment]
Outdated: the announcement link has been removed from the header altogether, since it often took a lot of space while not being that useful.
