### ISSUE TITLE
Nudge people to add links and platform tags

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#257]
[Some people](https://alakajam.com/2nd-alakajam/114/shadow-worldy/) forget to add links to their game. Many (including me, apparently!) forget to add platform tags, which hurts their discoverability.

I'm thinking a big red bar above the "Save changes" button, saying that your entry is incomplete and why.

**Comment by mkalam-alami** [comment]
We should also make it more visible to other people that the game has no links, eg. with a small "Incomplete" label directly on the thumbnail.

**Comment by mkalam-alami** [comment]
Done, extracted the bonus stuff into #627
