### ISSUE TITLE
Disable the "save changes" button when ratings are already saved

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#261]
When ratings are already given, replace the label with "Ratings saved!".

Use JS to restore the button label & enablement when we start clicking stars.

**Comment by Thrainsa** [comment]
@mkalam-alami I don't really think this is needed. The save button is clearly for the comment post.

**Comment by mkalam-alami** [comment]
Yes, 95202ff3c was made since and already made things clearer.

Closing the issue.
