### ISSUE TITLE
Game titles with certain special chars are butchered in the URLs

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#262]
See https://alakajam.com/2nd-alakajam/180/full-blockfull-blockfull-blockfull-blockfull-blockfull-blockfull-blockfull-block-wheres-full-blockfull-blockfull-blockfull-blockfull-blockth/

**Comment by ttencate** [comment]
Does this actually need fixing? I thought it was funny and entirely fitting for Aurel's game :)

In general, the `slug` package does its best to handle special chars sensibly, e.g.:

```
print(slug('i ♥ unicode'))
// > i-love-unicode 
 
print(slug('unicode ♥ is ☢')) // yes! 
// > unicode-love-is-radioactive
```

So we seem to have a choice between letting that happen, or allowing only a small subset (like ASCII and ASCII-like characters) and replacing (sequences of) other characters by a single `-`. Anything in between is a quagmire of special cases.

**Comment by mkalam-alami** [comment]
We definitely don't want to be dealing with special cases, ideally slug should just prefer removing special chars rather than translating them into words.

Just a matter of picking the right options in the lib I think.
