### ISSUE TITLE
Text baseline too high in Firefox

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#264]
Everything looks fine in Chrome, but in Firefox, text labels are often sitting too high in their respective boxes. For example, here on `ANNOUNCEMENT` and `Up next!`:

![2018-03-26-100405_556x212_scrot](https://user-images.githubusercontent.com/90930/37894040-18c8efe6-30dd-11e8-81c2-6bb182fbf363.png)

Also visible on theme upvote/downvote buttons, `Solo`/`Team`/`Unranked` buttons on the Games page, `Solo`/`Team`/`Unranked` labels on games, and various other places.

**Comment by mkalam-alami** [comment]
Cannot reproduce on latest Firefox & Chrome
