### ISSUE TITLE
Like system for posts

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#271]
And only posts.

* Store all likes in a dedicated table, with one row per user-like
* Only auth'd users can like
* Likes are public, ie. we can see the list of who liked what, like on Twitter
* Also store the like count on the post

**Comment by NiciusB** [comment]
I was going to write an issue about this, but I see that you guys have that already planned. Awesome!

As food of thought, I'd love to also see likes for comments, and even reactions with emojis (ala slack) instead of just likes. I know it's a lot more work but it'd be a lot cooler 💕

**Comment by mkalam-alami** [comment]
Oh having a variety of emojis as reactions to posts would be great!

Regarding likes for comments, when we discussed them on IRC & Twitter they turned out more controversial: the main fear was that they could push people to make more consensual/nice comments, while what we're looking for is really honest criticism & discussions about the games.

So yeah we'll just introduce likes on post for now (as soon as someone finds the time to contribute them :smile:) and see where it goes from here!

**Comment by mkalam-alami** [comment]
A simple like feature is implemented for now, but the DB model is made so we can support multiple types of likes in the future.
