### ISSUE TITLE
Markdown shorthand for strike-through text isn't rendered properly

### ISSUE THREAD

**Issue by coxm** [alakajam-team/alakajam#274]
To reproduce:
- Create a post containing `~~crossed-out text~~`.
- Preview the post; the text is displayed in a `<del>` element, like ~~crossed-out text~~.
- Publish the post; the text is rendered in a `<p>` with no strike-through effect.

**Comment by mkalam-alami** [comment]
Fix is online, the Kajam post is no longer inviting AIs to CRUSH ALL HUMANS :D
