### ISSUE TITLE
Trace pages that take a long time to load

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#275]
We have some cases of people seeing the website become suddenly super slow for a moment.

In order to see if this is on the server side, let's log all requests that take >1s to load, with some relevant information like:
* The time of the query
* The URL & HTTP method
* The user that requested the page

**Comment by ttencate** [comment]
Also maybe we could log slow db queries, whether or not they are tied to
slow page loads.

**Comment by mkalam-alami** [comment]
Done. I have enabled logging of long requests & queries on the live site:

```
  // Debug: trace options
  LOG_LEVEL: 'warn', // Verbose level among 'none', 'error', 'warn', 'info', 'debug'
  DEBUG_TRACE_SQL: false, // Traces all SQL calls
  DEBUG_TRACE_SLOW_SQL: 500, // Traces SQL calls taking more than the specified time (in milliseconds, use -1 to disable)
  DEBUG_TRACE_REQUESTS: false, // Enables Express debug mode to trace request routes & timing
  DEBUG_TRACE_SLOW_REQUESTS: 1000 // Traces HTTP requests calls taking more than the specified time (in milliseconds, use -1 to disable)
```
