### ISSUE TITLE
SimpleMDE behaves strangely on mobile

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#287]
The comment box is completely erratic, with space being cancelled and backspace seemingly serving as a copy/paste of sorts. Super weird

EDIT: Confirmed to have similar issues on the SimpleMDE demo

**Comment by ttencate** [comment]
Not [the first](https://github.com/alakajam-team/alakajam/issues/193) SimpleMDE bug. Combined with the fact that we have two different CodeMirror versions embedded now<sup>[citation needed]</sup>, maybe a reason to see if there's something better out there?

**Comment by mkalam-alami** [comment]
Leaving this here

* https://github.com/nhnent/tui.editor
* http://markitup.jaysalvat.com/home/

**Comment by mkalam-alami** [comment]
I have started to look into the TUI Editor a bit on branch `tui-editor` (not working atm).

It uses CodeMirror as well so it still needs your #193 fix, but it doesn't have the SimpleMDE issue on Android.

**Comment by mkalam-alami** [comment]
This was fixed by the EasyMDE fork, which was a drop-in replacement. Switching to a more active project would still be good, but it's less a priority now.

Closing this, #215 will let us look closely at that possible double CodeMirror issue.
