### ISSUE TITLE
Allow for MP4 uploads in high score proofs

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#290]
Of course we'll keep 2MB as a size limit for them as well.

Make sure a video camera icon appears (like for YouTube) instead of the default one.

More importantly: does this have a security implication?

**Comment by Aurel300** [comment]
As with any upload, we want to make sure people cannot choose their own filename, the path we create is unpredictable and made out of a random number (based on time) and has the "mp4" extension, the video playback should just be a `<video>` element. More importantly MP4 is a container, not a codec. We might want to:

 - check for filesize (< 2 MiB)
 - check for file header (see https://www.garykessler.net/library/file_sigs.html and search MP4)
 - run a `ffprobe` to check resolution (have some reasonable minimum and maximum), aspect ratio, and video length; also check that there is one video stream and one audio stream
 - re-encode with `ffmpeg`

**Comment by mkalam-alami** [comment]
Closing as low priority
