### ISSUE TITLE
User registration captcha

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#292]
The time has come. We finally have our first bot accounts on Alakajam.

~An option would be to integrate an [invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible).~ No need to integrate heavy libs for now. The "Are you human?" question trick did great so far. Try completing (replacing?) it with Aurel's suggestion below.

**Comment by mkalam-alami** [comment]
\*bot account creation speed intensifies\*

**Comment by mkalam-alami** [comment]
Added a basic "Are you human? (yes or no)" question for starters, this should keep most evil bots at bay.

**Comment by Aurel300** [comment]
One useful anti-spam technique is to add an innocuous-looking field to the form, that just asks for e.g. e-mail. But hide it with CSS using `position: fixed; top: 0; left: -1000px;` for example. So a user will never put anything in that field but a bot will happily put some e-mail thinking it is required for registration.

**Comment by mkalam-alami** [comment]
This might need an upgrade as we've have a small batch of similar fake users using their profile for advertising. Avatars, social links and bios are nicely filled so it might be manual spam or a tailor-made bot.
