### ISSUE TITLE
"Save comment & ratings" only saves the ratings if there is a comment

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#299]
* `npm run watch`
* Go to http://localhost:8000/2nd-alakajam/11/game-9/
* Put 10 stars on Overall
* Click "Save comment & ratings"

Expected: ratings are saved and we see 10 stars.

Actual: ratings are not saved, we still see empty stars.

If a nonempty comment is supplied, both are saved correctly.

**Comment by mkalam-alami** [comment]
I actually can't reproduce this, stars are saved fine for me.

**Comment by ttencate** [comment]
Hmm, it doesn't seem to always happen. If I just change some ratings a few times and click this button each time, it does eventually show up.

Node v8.11.2, using SQLite, freshly after deleting `data` and `node_modules` and running `npm install`.
