### ISSUE TITLE
Switch all session management to express-session, store sessions in database

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#306]
```
13:07:41 < thomastc> wan: I'm confused about the session stuff. we 
                     use express-session (cookie name 'connect.sid') 
                     but we also have our own session handling code 
                     (cookie name 'session')? express-session uses a 
                     MemoryStore, our own uses a JSON file. csurf 
                     uses req.session, which is the session managed 
                     by express-session
13:08:45 <@wan> it was cleaner before I introduced csurf
13:08:57 <@wan> express-session was added specifically for csurf
13:09:03 < thomastc> oh, I see
13:09:09 <@wan> because before that I didn't feel the need for 
                sessions
13:09:13 <@wan> only cookies 
13:09:19 <@wan> login cookies
13:09:38 <@wan> except for CSRF to work we need to have session mgmt 
                even when anonymous
13:09:48 <@wan> (log in/sign up form)
13:10:03 <@wan> I guess the ideal solution would be to integrate 
                csurf with our own cookie system
13:10:08 <@wan> which is possible iirc
```

**Comment by mkalam-alami** [comment]
Note: Until the session refactoring is done, hotfix the main flaw of the current system being the `session.json` file being written in an unsafe way (write lock required)

**Comment by ttencate** [comment]
After extended discussion on IRC, it was decided to:

* [ ] Store session data in the database (PostgreSQL in production, SQLite in development), using the appropriate [express-session stores](https://github.com/expressjs/session#compatible-session-stores). Look at the knex config to determine which type of store to use.

    Rationale: The currently used `MemoryStore` is explicitly not suitable for production use. It doesn't scale to multiple processes, and it doesn't survive a restart of the server process.

* [ ] Switch all session management over to express-session. The use of a JSON file goes away. `sessionService.js` goes away too.

    Rationale: the JSON file doesn't scale, and writing it is prone to race conditions even in the current single-process case.

* [ ] Implement "remember me" simply by extending the lifetime of the session cookie.

    Rationale: A [more secure approach](https://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website/244907#244907) exists. It offers some protection against cookie theft (because previous cookies become invalid as soon as the real user starts a new session) and against database leaks (knowing the hashed token from the database doesn't help an attacker to impersonate users). But this approach is harder to implement, and the things it protects against are usually symptoms of bigger problems (XSS and a compromised server, respectively).
