### ISSUE TITLE
Certain font-awesome icons don't work on old browsers

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#311]
"fa-circle-o" and "fa-star-o" in particular don't seem to show up in Firefox 29/Linux:

![clipboard02](https://user-images.githubusercontent.com/694508/41709615-e9352e24-7543-11e8-8820-ddcbe3c490d5.jpg)

This makes voting impossible. What's weird is that replacing the markup with other symbols works.

**Comment by ttencate** [comment]
There is a difference: the CSS rule for `fa-star` is duplicated in `font-awesome.min.css` (from Bootstrap CDN, `https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css`) and in our own `index.css`, but `font-star-o` is only present in `font-awesome.min.css` and not in our own CSS.

**Comment by ttencate** [comment]
We shouldn't even be using the Bootstrap CDN. The Font Awesome CSS is being `@include`d into our own `index.css`. But we are somehow getting the CDN link through EasyMDE... if I comment out the line that loads `easymde.min.js`, then we see the same breakage in the latest Firefox as well.

Let's see if we can potty-train EasyMDE...
