### ISSUE TITLE
Add SCSS (SASS) support

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#313]
PostCSS is nice, but [sometimes](https://github.com/alakajam-team/alakajam/issues/312) you just want to write a for loop in CSS. Let's make that possible.

**Comment by mkalam-alami** [comment]
Done! The deprecated cssnext is now gone, sass is in.

The migration was not that hard in the end, the hardest part was more replacing some bits of postcss that were missing from sass (watch folders + copy static assets)
