### ISSUE TITLE
Rethink "Divisions" selector in games search form

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#315]
Currently it's confusing more than anything. Especially since we tried to take in account the alternate "ranked"/"unranked" divisions of the Kajams.

**Comment by ttencate** [comment]
Maybe a dropdown similar to Event?

    All divisions
    Solo
    Team
    Unranked

I can see a remote use case for enabling both Solo and Team (for people who want to give stars but not write comments), but I doubt it's worth supporting.
