### ISSUE TITLE
Some form editors are not autosaving

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#319]
Every invocation of `formMacros.editor` should be given a third argument, `autosaveId`, which should be unique site-wide. Two of them are missing though:

```
$ ag formMacros.editor\\b 
templates/post/_macros-post.html
209:        {{ formMacros.editor('body', comment.get('body') if comment) }}

templates/post/edit-post.html
53:      {{ formMacros.editor('body', post.get('body')) }}

templates/event/edit-event-themes.html
79:    {{ formMacros.editor('elimination-body', eventDetails.get('shortlist_elimination').body) }}
...
```

The first one is used for all comments (both on entries and on posts). The second is for editing posts. So two of the most important ones are missing. The third one is for admin use only, probably not critical.

**Comment by ttencate** [comment]
I'm wondering if we should generate this ID automatically, based on (the hash of?) the concatenation of:

* current URL path (so we're excluding domain, query string, fragment) +
* the `action` of the current form +
* the `name` of the form field.

On the one hand, this fixes all occurrences now and in the future. On the other hand, it might result in false negatives, e.g. the same comment form being visible on two different URL paths. But I think these cases are rare enough. And we're not trying to save anything for posterity here, we just want to survive a page refresh or two.

**Comment by mkalam-alami** [comment]
Made obsolete following #354
