### ISSUE TITLE
Reorder Links

### ISSUE THREAD

**Issue by SmBe19** [alakajam-team/alakajam#321]
It would be very nice to be able to reorder the links for a game. For example in my import of my LD39 game the source link was missing (error on LD's part, is not displayed there even though it is saved...) and I had to manually add it. I would like to have the same order of links for all my games (source top entry).

I know you could just manually copy everything down one line to add something at the top, but it would be nice to be able to reorder the entries more easily.

**Comment by mkalam-alami** [comment]
Good idea, plus it's easy to do by reusing the code from the theme shortlist. Done
