### ISSUE TITLE
Submit Alakajam to indiegamejams.com

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#333]
http://www.indiegamejams.com/. The site seems to be pretty active and might drive some traffic.

If there is a playbook for running new (Alak|K)ajams, maybe make a note there as well.

**Comment by mkalam-alami** [comment]
Yup it's already done for each Alakajam (and on our event check-list).

This reminds me however that:
- We don't have check-lists for Kajams
- We haven't submitted the upcoming Kajam yet :)

**Comment by ttencate** [comment]
Oh, I didn't find Alakajam when I searched. I guess it only works for current/upcoming events then.

**Comment by mkalam-alami** [comment]
Yes, also we can only submit events one month-ish in advance unfortunately.
