### ISSUE TITLE
user.is_mod and user.is_admin should be booleans

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#339]
They're currently varchar(255). This needs a little DB migration.

**Comment by Aurel300** [comment]
What were you thinking? x)

**Comment by mkalam-alami** [comment]
Copy pasting is evil https://github.com/alakajam-team/alakajam/blob/master/migrations/0001_init.js#L24

**Comment by mkalam-alami** [comment]
Duplicate of #464
