### ISSUE TITLE
[Server] Consider switching from forever to pm2

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#344]
pm2 seems more powerful and reliable.

1. Switch alakajam-irc to pm2 (@coxm)
2. If a success, switch everything else (@mkalam-alami)

**Comment by coxm** [comment]
1 is done :smile:

**Comment by mkalam-alami** [comment]
Everything has been switched during AKJ4.

I feel the `restart.sh` scripts are not even that necessary now: I've started to get used to always run `pm2 restart alakajam`, `pm2 logs alakajam`, etc. so let's just switch officially to these.

Keeping the issue open for us to update the admin documentation.
