### ISSUE TITLE
PSQL errors are no longer caught

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#353]
I can't seem to be able to catch PSQL errors anymore, to display 500s in a pretty page.

I've had the same issue with multer as well, but I've been able to [wrap multer](https://github.com/alakajam-team/alakajam/blob/master/controllers/index.js#L170) to force catching any errors.

I feel something's wrong with our integration of `express-promise-router` but I can't put my finger on it. Back to jamming for now...

**Comment by Aurel300** [comment]
Of course we read it.

**Comment by dollarone** [comment]
read what?
    On Tuesday, 22 January 2019, 20:45:29 GMT, Aurel <notifications@github.com> wrote:  
 
 
Of course we read it.
