### ISSUE TITLE
When creating entry, game description is sometimes copied from a previous entry

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#354]
Happened to @Aurel300  and @dollarone so far. But not me.

This may be related to either them being mods, or having entered the 5th Kajam.

@dollarone @Aurel300 If you have additionnal context feel free to add in, thanks.

**Comment by mkalam-alami** [comment]
It might just have happened to my entry.

**Comment by mkalam-alami** [comment]
Another report from the last Alakajam (by Tim):

![](https://media.discordapp.net/attachments/554287358699241472/625786298103365632/20190923161058_screenshot.png)

> Dunno if this has been seen or reported, but my detailed description was pre filled with contents of what seems to be Feedback Fortnight and Rally of Rockets.

**Comment by ttencate** [comment]
This is probably related to autosave. We are setting `autosaveId`, which gets passed to the `data-autosave-id` attribute, [here](https://github.com/alakajam-team/alakajam/blob/master/server/entry/manage/entry-manage.html#L238). It's set to `entry-details-${id}`.

And while I'm writing this, I realize what might be the problem for new entries. And yes:
![2019-11-04-082111_965x35_scrot](https://user-images.githubusercontent.com/90930/68104634-1c25a480-fedc-11e9-92ee-87801ec8b406.png)

A simple fix would be to use something like `'entry-details-' + (entry.get('id') || ('event-' + event.get('id')))`. I don't have time to fix and test this but I'll tag it as a good beginner's issue.

**Comment by mkalam-alami** [comment]
Great find, it's most probably the root issue. Quite a relief to find it at last :)

**Comment by mkalam-alami** [comment]
In the end I completely disabled the autosave feature.

Because entries are shared between all team members, I think descriptions can be messed with if:
1. A team member fills the description of an entry
2. Another team member edits the entry later having an autosaved description in his cache.
I suspect that's what happened to my own AKJ7 entry.

For now it's only an issue for entries, not posts, but we might eventually open up shared rights to blog posts in the future so I prefer to be cautious.
