### ISSUE TITLE
Post creation: Display a warning to prevent asking for votes

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#359]
We're starting to have quite a few people posting requests to get their games rated. The annoying part is that some of them haven't rated games themselves (the karma gives it away), nor have any [particular excuse](https://alakajam.com/post/878/im-busy-and-cant-rate-games).

A diplomatic solution would be to display a warning directly on the post creation page: if a player doesn't have enough ratings yet, display a warning like:

> **Theme voting in progress!** Please avoid posting just to ask for votes. Instead, take some time to review games: your karma*[link]* will then increase and you will reach the minimum votes faster!

On the other side, people like to spread their excitement by making a blog post once. Maybe we should restrict this to people having already posted a first time? Or adapt the warning to explicitly tolerate 1 "ad blogpost"?

**Comment by mkalam-alami** [comment]
Suggested additions/alternatives:

* Mod tool: Shadowbanning posts
* Requiring to rate a certain number of games to post or even get a ranking
* Limit somehow the number of posts, especially during the rating phase

**Comment by coxm** [comment]
I actually think a limit on the number of posts during the ranking phase is a pretty good idea. It's incredibly simple, and would have the desired effect. The only downside seems to be that people might have legitimate reasons to post (say, about another jam, or something technical, etc.); but in these rare cases perhaps a mod could decide.
