### ISSUE TITLE
Have a page dedicated to unranked entries in the Results section

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#365]
This suggestion was posted on the 4th AKJ survey, and indeed there's no reason not to show them somehow in that page.

* Display all the games inside the podium widget over three columns
* Maybe sort them by descending karma (but it a secret ordering because unranked should be unranked)
* Maybe do something fun like showing a gold medal on every game for completing the event

**Comment by Thrainsa** [comment]
I create the result page for unranked entries but not exactly like you thought :)
