### ISSUE TITLE
Display game info above game comments on mobile

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#381]
Game pages are not very mobile-friendly currently, as the whole info block is below the comments. Possible solutions:

1. Make the comments foldable on mobile + folded by default
2. Make a 2nd, simplified info + links block that replaces the main one on mobile resolutions
3. Reword the layout with flexbox

**Comment by Thrainsa** [comment]
I use method:
4. Rework the layout adding a float: right on the info for pc resolution :)

I tried to rework the layout using flexbox but I could get something good :(

**Comment by mkalam-alami** [comment]
Yeah CSS grids would have probably been much easier than flexbox, but we would have risked browser support issues again....

Thanks for the fix :)
