### ISSUE TITLE
Display issues with Unordered lists on game page

### ISSUE THREAD

**Issue by jasonleekennedy** [alakajam-team/alakajam#393]
unordered markdown list previews correctly, but doesn't display correctly on game page.  See here:

https://alakajam.com/5th-alakajam/584/artificial-elemental-expedition-prototype/

code on page currently - however all show up with same level of indentation on actual page
```
* KB/Mouse
  * WASD - Move
  * Mouse - Camera
  * Space Jump
  * Right mouse - Use Ability
  * ESC - pause menu

* Controller (XBox)
  * Left stick - Move
  * Right stick - Camera
  * Y - Jump
  * X - Use Ability
  * Start - Pause
```

**Comment by ttencate** [comment]
This is normal. Markdown requires you to indent nested lists with four spaces, not two. E.g. here on GitHub, this...

```markdown
* Level 1
  * Still level 1
    * Level 2
```

... is rendered as:

* Level 1
  * Still level 1
    * Level 2

**Comment by jasonleekennedy** [comment]
interesting... this works... also works in the preview <shrug>
```
* level 1
  * level 2
    * level 3
```
* level 1
  * level 2
    * level 3

**Comment by jasonleekennedy** [comment]
so i guess this is an issue with the preview window then?

**Comment by ttencate** [comment]
They use different parsers, I guess. For now just use four spaces, which always works :)

**Comment by mkalam-alami** [comment]
Apparently EasyMDE uses Codemirror's in-house [GFM parser](https://codemirror.net/mode/gfm/), which does yield different results than [Showdown](https://github.com/showdownjs/showdown). Maybe we could make the latter match the former by using its GFM preset "flavor".

If it doesn't help, as a backup for this problem in particular Showdown has a `disableForced4SpacesIndentedSublists` option that should provide support for 2-spaces sub-list indentation. It would be a reasonable change.

**Comment by mkalam-alami** [comment]
A few clarifications to make this all more accessible:

* EasyMDE is the lib we use as the rich text editor, which itself wraps another lib called Codemirror
* Showdown is the lib we use on the server-side to actually render the posts
* There are multiple, different specifications of Markdown:
  * The one used by EasyMDE is that "GFM" thing (for Github Flavored Markdown), which we can't easily change I think
  * Showdown only enables classic Markdown by default but does seem to support GFM. We can easily configure that in our code (`core/forms.js`)

**Comment by ttencate** [comment]
Agreed. GFM is definitely the superior dialect. More intuitive (see e.g. this issue) and more feature-rich (e.g. code blocks with triple backticks).
