### ISSUE TITLE
Strange date format

### ISSUE THREAD

**Issue by Aurel300** [alakajam-team/alakajam#421]
![Screen Shot 2019-05-27 at 22 19 33](https://user-images.githubusercontent.com/1102162/58439732-a700a880-80cd-11e9-8de5-df9018a2a758.png)

**Comment by mkalam-alami** [comment]
Thanks, the problem was between the chair and the keyboard

**Comment by Aurel300** [comment]
Also showing on AKJ5:

![Screen Shot 2019-05-31 at 15 07 49](https://user-images.githubusercontent.com/1102162/58711212-f1c43e00-83b5-11e9-9e39-6110ac21663e.png)

**Comment by mkalam-alami** [comment]
Done
