### ISSUE TITLE
Latest Firefox finds an analytics cookie to block

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#427]
We're not supposed to use cookies, see if we forgot to disable something.

**Comment by Aurel300** [comment]
We do have Google Analytics though?

**Comment by mkalam-alami** [comment]
@Aurel300 Yep! You should have access to it https://analytics.google.com/analytics/web/#/

**Comment by mkalam-alami** [comment]
They are caused by embeds, in particular Youtube embeds. We also authorize Twitch, Vimeo and Gfycat embeds so we should look into disable any cookies they might use.

**Comment by mkalam-alami** [comment]
Phew, media embeds are very bad when it comes to tracking cookies. Other than YouTube none of our whitelisted sites had options to disable tracking. Which means supporting any of them forces us to have an "Accept cookie" thing to stay RPGD-compliant.

I have removed support for all blog post embeds except YouTube (I'm sure they were not used anyway).

Twitch is more of a problem as we use it on the front page for launch events, I'll open a separate issue for it.
