### ISSUE TITLE
Error 500 when you rate a game

### ISSUE THREAD

**Issue by Thrainsa** [alakajam-team/alakajam#433]
Way to reproduce:
 - Go to a game done for the climate change jam
 - Click on a star to add ratings
 - You get this message: **Failed to save ratings: Internal Server Error. Enter another rating to retry.**

The ratings seems to have been saved even with this message

**Comment by mkalam-alami** [comment]
Probably related stacktrace:

```
2019-08-20 12:17:44.565 ERROR (/server/core/log.ts:45) HTTP 500: Something went wrong, sorry about that.
TypeError: entry is not a function
    at entrySaveCommentOrVote (/data/www/alakajam/server/entry/entry-view.controller.ts:107:5)
    at <anonymous>
```

**Comment by mkalam-alami** [comment]
The regression was introducted when refactoring the controller files. It's fixed.
