### ISSUE TITLE
Theme voting "alignment": show a positive/negative ratio chart

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#445]
Show a ratio of votes casted, both for ourselves and overall.

* Bonus: add alignment nicknames
* Bonus 2:  use full D&D alignments with "Lawful good" being a higher-than-average  positive ratio + a higher-than-average correlation with the overall trend. "Chaotic evil" is low positive ratio and low correlation with other people.

It's dumb but it sounds fun.

**Comment by Aurel300** [comment]
Is this after the themes are selected, or when entering the top 10 phase…?

**Comment by mkalam-alami** [comment]
I'd see it as a live pie chart or something, showing maybe a pie graph indicating 30% of your votes are positive. Just a small gamification thing.

**Comment by mkalam-alami** [comment]
Moved to the [Feature requests](https://github.com/alakajam-team/alakajam/wiki/Feature-requests) page for now.
