### ISSUE TITLE
Create an iCalendar feed of events

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#447]
Google Calendar lets you create a calendar from an URL that points to an [iCalendar file](https://en.wikipedia.org/wiki/ICalendar), and will automatically refresh it every day. I [think](https://support.apple.com/en-us/HT202361) Apple has something like that too.

I think this could really help for people to keep their schedule clear during the main events, and drive up participation. As a bonus, users could set reminders on these evens so you get a notification on your phone an hour before the deadline ;)

There could also be an official Google Calendar that people could add, to make the process of adding it slightly smoother.

As usual, the npm ecosystem is a quagmire of unmaintained packages and forks, but I think https://www.npmjs.com/package/ics-plus is our best bet for generating these (https://www.npmjs.com/package/@koumoul/icalendar being the runner-up). It shouldn't be too hard to it with our own ad-hoc code either.

**Comment by mkalam-alami** [comment]
Moved to the [Feature requests](https://github.com/alakajam-team/alakajam/wiki/Feature-requests) page for now.
