### ISSUE TITLE
"Incremental" backups

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#454]
> ⚠️ I'm keeping a trace here but this issue is not resolved by committing code here.

We don't need to keep multiple copies of file uploads. We can save space by only keeping a ZIP history of the database dump, and in parallel have a single ZIP hold a backup of the static files.

**Comment by ttencate** [comment]
Got my head in backups too at the moment, albeit for different reasons...

I'm quite fond of [borg backup](https://www.borgbackup.org/), which can do compression, deduplication, encryption, validation and expiry all out of the box. There are [third parties](https://www.borgbackup.org/support/commercial.html) that offer Borg hosting, but self-hosting is straightforward too.

**Comment by mkalam-alami** [comment]
I confirm, borg is great! I can only recommend it as well.

It was easy enough to set up on the Alakajam server, now we finally don't have to sacrifice backup history for disk space 🌈
