### ISSUE TITLE
Replace unranked jam emoji

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#455]
https://twitter.com/LiamLimeGames/status/1182617271996440580?s=19

**Comment by pta2002** [comment]
Heh I can work on this. Just to be sure, we want ✌️ instead right?

**Comment by pta2002** [comment]
Huh, I'm looking at the code and it seems like it's just defined as `fa-peace-sign`, so font-awesome says that's a peace sign

**Comment by mkalam-alami** [comment]
@pta2002 Yeah that's what I argued, but there could be a difference between the palm facing inward or outward. I don't mind changing it + opening an issue at Font Awesome and watch them investigate :P

**Comment by mkalam-alami** [comment]
Bug report: https://github.com/FortAwesome/Font-Awesome/issues/15751

**Comment by mkalam-alami** [comment]
After a quick Discord poll the one that seems best is https://fontawesome.com/icons/hat-wizard?style=solid (available  since 5.11 so it means a lib upgrade is required)
