### ISSUE TITLE
Support hosting tournaments on actual jams

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#475]
- [x] Currently there are a few limitations preventing to host both within the same Alakajam event. Removing them should not be too hard and could give us more freedom to bring some variation to the events.

**EDIT: Regaining header space**

- [x] Move "Rules" link to the dashboard.
- [x] (If needed) Move "Posts" link to the dashboard (temporary solution).

**Comment by Thrainsa** [comment]
closed by: [ca20ee3](https://github.com/alakajam-team/alakajam/commit/ca20ee3c131dce7688a82c9427416e37bcb9120e)
