### ISSUE TITLE
Markdown preview does not match actual display

### ISSUE THREAD

**Issue by SmBe19** [alakajam-team/alakajam#505]
The Markdown preview for a comment sometimes displays something different from what then is displayed once the comment is saved. In particular, the following will be displayed differently:

```
<details>
<summary>SPOILER</summary>
Some text that is a spoiler.
</details>
```

The preview shows this as I intended it. However, on the game page it was then displayed differently.

**Comment by mkalam-alami** [comment]
The details/summary tags where cleaned from the HTML, they are not whitelisted.Thank
