### ISSUE TITLE
"Web" icon has become a newspaper

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#506]
I think this used to be a globe?

![2020-03-01-130143_412x33_scrot](https://user-images.githubusercontent.com/90930/75625306-338c4a00-5bbd-11ea-935c-6281766e23ed.png)

Repro e.g. on https://alakajam.com/8th-alakajam/866/core-drop/, visible in both Firefox and Chromium on Arch Linux on My Machine™. The CSS class is `fa-newspaper` but I can't find this in the code, except in relation to blog posts...

**Comment by mkalam-alami** [comment]
Thanks for the reminder, it's already fixed but wasn't live yet.

It's indeed an accident (I migrated post-related icons to the newspaper with a bold search/replace).
