### ISSUE TITLE
Registering streamer doesn't trigger a tournament leaderboard refresh

### ISSUE THREAD

**Issue by Thrainsa** [alakajam-team/alakajam#534]
If a streamer user has scores and register after as a streamer, the leaderboard isn't refreshed. He need to add a new highscore for it

**Comment by mkalam-alami** [comment]
Currently registering as a streamer is only possible before the tournament starts, so I didn't take the time to handle this corner cases.

But why not support it, just in case we decide to keep registrations open! Normally all we need to do is add a call to `tournamentService.refreshAllTournamentScores()` at the right place.
