### ISSUE TITLE
Shortlist message introduces it as already sorted

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#536]
Even before sorting the shortlist, the page already says:

> Here are the top submitted ideas as you ranked them. You can still drag'n'drop them to change the order. 

(Unless I misclicked...)

**Comment by Thrainsa** [comment]
It happens when you already votes for themes during the first vote phase.
I had this use case with the shortlist message:

> Here are the top submitted ideas as you ranked them during the first vote phase. You can still drag'n'drop them to change the order.
