### ISSUE TITLE
Front page: comments can be cut halfway through an image and break the layout

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#554]
![](https://media.discordapp.net/attachments/554287358699241472/724605426003345439/Screenshot_1.png?width=387&height=614)

**Comment by coxm** [comment]
Hey @mkalam-alami, can you give some idea of what the layout should look like here? Maybe it's just me but I'm not sure what's wrong. :smile:

**Comment by Aurel300** [comment]
@coxm The `![](https://imgur.co...` bit is Markdown syntax for an image cut in half. This should not happen, the "read more" bit should either be after the image, or before it. As it is, it seems to leave some tag unclosed, resulting in the remainder of the comments having pink text for some reason.

**Comment by coxm** [comment]
I  suspect this was fixed during the first hackathon. Please yell at me if I'm wrong though :)
