### ISSUE TITLE
Highlight the creator's own comments underneath their entries and blog posts

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#562]
Like Reddit has the microphone icon an a boldface name to highlight the OP. This is useful. Should we highlight the entire comment (e.g. with a different background colour) or just their name?

**Comment by mkalam-alami** [comment]
I like the Reddit-like name highlighting, the entire comment would be too much I think

**Comment by mkalam-alami** [comment]
I spent too long looking for a fitting icon (The microphone is not in the free font awesome pack, and not even that appropriate...). I went with a different metaphor.

![firefox_AT6KTs5h0s](https://user-images.githubusercontent.com/694508/85923773-28f17100-b88e-11ea-8171-ec091ce16343.png)

**Comment by ttencate** [comment]
Nice! Just having anything is way better than nothing, so I don't want to start a big bikeshedding discussion. So consider the icons below as inspiration :)

There are two microphones in the free pack, albeit with a different style than Reddit's:
https://fontawesome.com/icons/microphone?style=solid
https://fontawesome.com/icons/microphone-alt?style=solid

Something that says "boss":
https://fontawesome.com/icons/crown?style=solid

Or more like "creator":
https://fontawesome.com/icons/brain?style=solid
https://fontawesome.com/icons/pen-fancy?style=solid
https://fontawesome.com/icons/user-edit?style=solid

Or something abstract and neutral:
https://fontawesome.com/icons/splotch?style=solid

**Comment by mkalam-alami** [comment]
The available microphones made me think too much of audio channels/mute buttons and the likes... I think my favorite is `pen-fancy`, maybe even [pen-nib](https://fontawesome.com/icons/pen-nib?style=solid). I dismissed pens as too close to the edit buttons we have, but that particular style does say "author" more than "edit" I guess. `crown` is okay too, I considered `chess-king` but not that one.

**Comment by ttencate** [comment]
Thank you for repainting the bikeshed ;)
