### ISSUE TITLE
theme ranking strange behaviour

### ISSUE THREAD

**Issue by bremco** [alakajam-team/alakajam#580]
I was on Win64/Chrome when this happened.

![cards_on_top](https://user-images.githubusercontent.com/30440932/93466205-2d0cb800-f8ec-11ea-8d44-7f97e459253e.png)
![clockwork_on_top](https://user-images.githubusercontent.com/30440932/93466206-2da54e80-f8ec-11ea-8a6d-09386ca07f3e.png)

The pictures probably paint a better picture, but here are the actions I took to get them: I wanted to drag the themes (Clockwork) around, but when I saved, the top eliminated theme (Cards) got placed on 1 instead, and swapped with the theme I had dragged. I could reverse it by dragging the previously eliminated theme around, then saving, and Clockwork was back on top (... I had it at 2, but I was doubting that anyway and don't really dare touch it again).

Whatever happens, I more or less like all the themes, but that might not be the case for everyone :-)

**Comment by mkalam-alami** [comment]
Thanks for the report, I'll try to reproduce asap

**Comment by mkalam-alami** [comment]
Oh yeah there's clearly something broken

**Comment by mkalam-alami** [comment]
Fixed with 5126c86, the patch is online

**Comment by mkalam-alami** [comment]
Ok it's still not perfect, I'll have to add an additional rule to avoid themes just barely eliminated to get back into contention
