### ISSUE TITLE
Error when sending password reset emails

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#641]
(Or any email probably)

> Failed to send mail: 140049742096256:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: 

This is probably a config/environment setup issue.

**Comment by ttencate** [comment]
https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number suggests that this means trying to talk SSL to a non-encrypted port.

**Comment by mkalam-alami** [comment]
Ah this is an obsolete issue, it was fixed during the June jam. It was a configuration issue indeed
