### ISSUE TITLE
Rules page implies entries should be video-games only

### ISSUE THREAD

**Issue by pixelsyntax** [alakajam-team/alakajam#666]
https://alakajam.com/article/docs/alakajam-competition-rules reads "The Alakajam! competitions let people make a video game from scratch in a week-end". A recent unlinkable discord discussion clarified that non-video games are also permissable. The documentation should be updated to reflect by removing the implication from the introduction and perhaps by being explicit with examples of what kind of games are permissable.

**Comment by pixelsyntax** [comment]
Created a pull request #667 to remove 'video' requirement

**Comment by mkalam-alami** [comment]
Done with #667
