### ISSUE TITLE
Improve password encryption

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#86]
The current system uses SHA256 + a password-specific salt. While it's decent security-wise, it might not be enough in the long term.

- [ ] Set up a new encryption system based on bcrypt
- [ ] Have a new field store the passwords using that encryption (maybe with the hash type stored somewhere)
- [ ] Make a migration process that switches passwords to the new format as old users log in

**Comment by ttencate** [comment]
I'm going to assume that @pta2002 is not working on this right now, and steal this from him :)

**Comment by Aurel300** [comment]
This is an extremely low-priority issue. I feel like actually worrying about this is much more likely to break something / make the login experience slower / make the user tables heavier / etc.

**Comment by ttencate** [comment]
On second thought, I agree. I picked this up because it's fun to think about perfect security, but it's definitely good enough already. Going to spend some time elsewhere.

**Comment by ttencate** [comment]
Recording this here in case someone picks this up again: on the production system, 11 rounds of bcrypt takes 193 ms, which sounds like a reasonable number.

**Comment by mkalam-alami** [comment]
Closing this for now, but if there is interest the task can be picked up again.
